steps:
# Paso 1: Construir la imagen Docker
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 
    'europe-southwest1-docker.pkg.dev/$PROJECT_ID/gcp-vm-dashboard-backend-repo/gcp-vm-dashboard-backend:$COMMIT_SHA', # <--- Región y Nombre de Repo AR
    '.'
  ]
  dir: 'backend' # Importante: Indica que el Dockerfile está en la carpeta 'backend'

# Paso 2: Subir la imagen a Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push', 
    'europe-southwest1-docker.pkg.dev/$PROJECT_ID/gcp-vm-dashboard-backend-repo/gcp-vm-dashboard-backend:$COMMIT_SHA' # <--- Región y Nombre de Repo AR
  ]

# Paso 3: Desplegar la imagen en Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud' # <--- ¡CORRECCIÓN CRÍTICA AQUÍ!
  args: [
    'run', 'deploy', 'gcp-vm-dashboard-backend-service', # Nombre del servicio de Cloud Run
    '--image', 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/gcp-vm-dashboard-backend-repo/gcp-vm-dashboard-backend:$COMMIT_SHA', # <--- Región y Nombre de Repo AR
    '--region', 'europe-southwest1', # <--- Tu región
    '--platform', 'managed',
    '--allow-unauthenticated', # Permitir invocaciones públicas
    '--service-account', '780691668337-compute@developer.gserviceaccount.com', # <--- ¡CORRECCIÓN: Email completo de la cuenta de servicio!
    '--set-env-vars', 'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},JWT_SECRET=${_JWT_SECRET}' # Variables de entorno
  ]
  env:
    - 'CLOUDSDK_COMPUTE_REGION=europe-southwest1' # <--- Tu región
images:
- 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/gcp-vm-dashboard-backend-repo/gcp-vm-dashboard-backend:$COMMIT_SHA' # <--- Región y Nombre de Repo AR