# backend/cloudbuild.yaml
steps:
# Paso 1: Construir la imagen Docker del backend
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 
    'europe-southwest1-docker.pkg.dev/$PROJECT_ID/gcp-vm-dashboard-backend/gcp-vm-dashboard-backend:$COMMIT_SHA', 
    '.'
  ]
  dir: 'backend' # Importante: Indica que el Dockerfile está en la carpeta 'backend'

# Paso 2: Subir la imagen Docker a Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push', 
    'europe-southwest1-docker.pkg.dev/$PROJECT_ID/gcp-vm-dashboard-backend/gcp-vm-dashboard-backend:$COMMIT_SHA'
  ]

# Paso 3: Desplegar la imagen en Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud' 
  args: [
    'run', 'deploy', 'gcp-vm-dashboard-backend-service', # Nombre del servicio de Cloud Run
    '--image', 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/gcp-vm-dashboard-backend/gcp-vm-dashboard-backend:$COMMIT_SHA',
    '--region', 'europe-southwest1', # Tu región
    '--platform', 'managed',
    '--allow-unauthenticated', # Permitir invocaciones públicas
    '--service-account', '780691668337-compute@developer.gserviceaccount.com', # La cuenta de servicio con roles de Compute
    # --- ¡CORRECCIÓN CRÍTICA DE SEGURIDAD! USAR VARIABLES DE SUSTITUCIÓN ---
    '--set-env-vars', 'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},JWT_SECRET=${_JWT_SECRET},GCP_PROJECT_ID=${PROJECT_ID}'
  ]
  # --- Definimos las variables de Secret Manager para Cloud Build ---
  secretEnv: ['_GOOGLE_CLIENT_ID', '_JWT_SECRET'] 
images:
- 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/gcp-vm-dashboard-backend/gcp-vm-dashboard-backend:$COMMIT_SHA'

# --- Sección de secretos disponibles (al final del archivo, CRÍTICO para Secret Manager) ---
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/my-google-client-id/versions/latest # Nombre del secreto en Secret Manager
    env: '_GOOGLE_CLIENT_ID' # El nombre de la variable de sustitución en Cloud Build
  - versionName: projects/$PROJECT_ID/secrets/my-backend-jwt-secret/versions/latest # Nombre del secreto en Secret Manager
    env: '_JWT_SECRET' # El nombre de la variable de sustitución en Cloud Build

options:
  logging: CLOUD_LOGGING_ONLY

