# backend/cloudbuild.yaml
# Versión final y corregida

steps:
  # Paso 1: Construir la imagen Docker del backend
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Backend Image'
    args:
      - 'build'
      - '-t'
      - 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/gcp-vm-dashboard-repo/gcp-vm-dashboard-backend-service:$COMMIT_SHA'
      - '.'
    dir: 'backend'

  # Paso 2: Subir la imagen Docker a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Backend Image'
    args:
      - 'push'
      - 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/gcp-vm-dashboard-repo/gcp-vm-dashboard-backend-service:$COMMIT_SHA'

  # Paso 3: Desplegar la imagen en Cloud Run con los secretos correctos
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'gcp-vm-dashboard-backend-service'
      - '--image'
      - 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/gcp-vm-dashboard-repo/gcp-vm-dashboard-backend-service:$COMMIT_SHA'
      - '--region'
      - 'europe-southwest1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - '780691668337-compute@developer.gserviceaccount.com'
      # Pasamos las variables de entorno, usando las sustituciones de los secretos definidos abajo
      - '--set-env-vars'
      - 'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},JWT_SECRET=${_JWT_SECRET},GCP_PROJECT_ID=$PROJECT_ID'
    # --- LÍNEA ELIMINADA ---
    # La clave 'secretEnv' se ha eliminado de este paso porque ya usamos 'availableSecrets' abajo.

# --- Sección de secretos disponibles para TODO el proceso de build ---
# Esta es la única sección que necesitamos para manejar los secretos.
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/my-google-client-id/versions/latest
      env: '_GOOGLE_CLIENT_ID'

    - versionName: projects/$PROJECT_ID/secrets/my-backend-jwt-secret/versions/latest
      env: '_JWT_SECRET'

images:
  - 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/gcp-vm-dashboard-repo/gcp-vm-dashboard-backend-service:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY




