steps:
# Paso 1: Construir la imagen Docker
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 
    'europe-west1-docker.pkg.dev/$PROJECT_ID/gcp-vm-dashboard/gcp-vm-dashboard-backend:$COMMIT_SHA', 
    '.'
  ]
  dir: 'backend' # Importante: Indica que el Dockerfile está en la carpeta 'backend'

# Paso 2: Subir la imagen a Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push', 
    'europe-west1-docker.pkg.dev/$PROJECT_ID/gcp-vm-dashboard/gcp-vm-dashboard-backend:$COMMIT_SHA'
  ]

# Paso 3: Desplegar la imagen en Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: [
    'run', 'deploy', 'gcp-vm-dashboard-backend', # Nombre del servicio de Cloud Run
    '--image', 'europe-west1-docker.pkg.dev/$PROJECT_ID/gcp-vm-dashboard/gcp-vm-dashboard-backend:$COMMIT_SHA',
    '--region', 'europe-west1', # Tu región
    '--platform', 'managed',
    '--allow-unauthenticated', # Permitir invocaciones públicas
    '--service-account', '[NOMBRE_C780691668337-compute@developer.gserviceaccount.com]@$PROJECT_ID.iam.gserviceaccount.com', # La cuenta de servicio con roles de Compute
    '--set-env-vars', 'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},JWT_SECRET=${_JWT_SECRET}' # Variables de entorno
  ]
  env:
    - 'CLOUDSDK_COMPUTE_REGION=europe-west1' # Tu región
images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/gcp-vm-dashboard/gcp-vm-dashboard-backend:$COMMIT_SHA'