# backend/cloudbuild.yaml
steps:
# Paso 1: Construir la imagen Docker
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 
    'europe-southwest1-docker.pkg.dev/$PROJECT_ID/gcp-vm-dashboard-backend/gcp-vm-dashboard-backend:$COMMIT_SHA', 
    '.'
  ]
  dir: 'backend' # Importante: Indica que el Dockerfile está en la carpeta 'backend'

# Paso 2: Subir la imagen a Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push', 
    'europe-southwest1-docker.pkg.dev/$PROJECT_ID/gcp-vm-dashboard-backend/gcp-vm-dashboard-backend:$COMMIT_SHA'
  ]

# Paso 3: Desplegar la imagen en Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud' # Indica que 'gcloud' es el ejecutable
  args: [
    'run', 'deploy', 'gcp-vm-dashboard-backend-service', # Nombre del servicio de Cloud Run
    '--image', 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/gcp-vm-dashboard-backend/gcp-vm-dashboard-backend:$COMMIT_SHA',
    '--region', 'europe-southwest1', # Tu región
    '--platform', 'managed',
    '--allow-unauthenticated', # Permitir invocaciones públicas
    '--service-account', '780691668337-compute@developer.gserviceaccount.com', # La cuenta de servicio con roles de Compute
    '--set-env-vars', 'GOOGLE_CLIENT_ID=780691668337-fagffk8595v6cdasflrj5pbpcoloc96d.apps.googleusercontent.com,JWT_SECRET=1823ca911266eafe96c0b42a9331fc097b1a84a974e4e206208685d93dc37bddd2c68fa9a094548da1ad5a3f3936a9fc1d5b6d7d80c684494c60654c07bb197984f34ac1e6ea34ce3d9a6a4e89a3dfbbb1081c1bf5752102e9bf782e3bd3c1711f83035b2c0248c32be814eefa615590b0eb7c946d0adfed5cc4f726eb0ec343a8859c91b4fcb7f7b91e5e2cc626daf4bfb3bcc81298177f494f21fb8d9068b76ebcde811d097152761203e03550c60bc2052130fae3411baf5a5b7d333d6497795fea3e5ad8132ba2508644ed73c394c1046936aa1ad9e994da6f6dd6610ac80bfc9adff55009d401033917daee194fbbdcc1c38732be40e83b8bd35f66f5e5,GCP_PROJECT_ID=puestos-de-trabajo-potentes' # Variables de entorno
  ]
  env:
    - 'CLOUDSDK_COMPUTE_REGION=europe-southwest1' # Tu región
images:
- 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/gcp-vm-dashboard-backend/gcp-vm-dashboard-backend:$COMMIT_SHA'